package ServiceTests;

import org.junit.Before;

import junit.framework.TestCase;
import net.itca.dwm.data.UserService;

/**
 * The class <code>UserServiceTest</code> contains tests for the class {@link
 * <code>UserService</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 10/12/14 17:03
 *
 * @author Dylan
 *
 * @version $Revision$
 */
public class UserServiceTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public UserServiceTest(String name) {
		super(name);
	}
	
	
	@Before
	public void setup()
	{
		
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = ServiceTests
 * package.sourceFolder = DineWithMeCore/tests
 * superclassType = junit.framework.TestCase
 * testCase = UserServiceTest
 * testClassType = net.itca.dwm.data.UserService
 */